<?php
require_once __DIR__ . '/../config/db.php';

$pdo = getDBConnection();
$user = requireFounder();
$action = $_GET['action'] ?? 'download';

if ($action === 'download') {
    // Generate SQL backup string
    $tables = ['users', 'categories', 'suppliers', 'medicines', 'purchases', 'purchase_items', 'customers', 'sales', 'sale_items', 'prescriptions', 'prescription_items', 'settings', 'branches', 'activity_logs'];

    $dump = "-- MCPMS DATABASE BACKUP DUMP\n";
    $dump .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
    $dump .= "-- Generated by Founder: " . $user['full_name'] . "\n\n";
    $dump .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

    foreach ($tables as $table) {
        $stmt = $pdo->query("SELECT * FROM `{$table}`");
        $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $dump .= "-- Table: `{$table}`\n";
        $dump .= "TRUNCATE TABLE `{$table}`;\n";

        foreach ($rows as $row) {
            $cols = array_map(function($c) { return "`{$c}`"; }, array_keys($row));
            $vals = array_map(function($v) use ($pdo) {
                if ($v === null) return 'NULL';
                return $pdo->quote($v);
            }, array_values($row));

            $dump .= "INSERT INTO `{$table}` (" . implode(', ', $cols) . ") VALUES (" . implode(', ', $vals) . ");\n";
        }
        $dump .= "\n";
    }

    $dump .= "SET FOREIGN_KEY_CHECKS=1;\n";

    logActivity($pdo, 'Database Backup Download', 'Founder exported full database SQL dump.');

    header('Content-Type: application/sql');
    header('Content-Disposition: attachment; filename="MCPMS_Backup_' . date('Ymd_His') . '.sql"');
    echo $dump;
    exit;
}

if ($action === 'restore' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!isset($_FILES['sql_file']) || $_FILES['sql_file']['error'] !== UPLOAD_ERR_OK) {
        responseJSON(['status' => 'error', 'message' => 'Please upload a valid .sql backup file.'], 400);
    }

    $sqlContent = file_get_contents($_FILES['sql_file']['tmp_name']);
    if (empty($sqlContent)) {
        responseJSON(['status' => 'error', 'message' => 'Uploaded file is empty.'], 400);
    }

    try {
        $pdo->exec("SET FOREIGN_KEY_CHECKS=0;");
        $pdo->exec($sqlContent);
        $pdo->exec("SET FOREIGN_KEY_CHECKS=1;");

        logActivity($pdo, 'Database Restore', 'Founder restored database state from uploaded SQL file.');
        responseJSON(['status' => 'success', 'message' => 'Database restored successfully!']);
    } catch (Exception $e) {
        responseJSON(['status' => 'error', 'message' => 'Restore failed: ' . $e->getMessage()], 400);
    }
}

responseJSON(['status' => 'error', 'message' => 'Invalid backup action.'], 400);
